# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"PairwiseDistance": "00_distance.ipynb",
         "pairwise_dist_gram": "00_distance.ipynb",
         "stackoverflow_pairwise_distance": "00_distance.ipynb",
         "PairwiseDistance.stackoverflow_pairwise_distance": "00_distance.ipynb",
         "torch_pairwise_distance": "00_distance.ipynb",
         "PairwiseDistance.torch_pairwise_distance": "00_distance.ipynb",
         "measure_execution_time": "00_distance.ipynb",
         "get_time_stats": "00_distance.ipynb",
         "DistanceMatrixIndexMapper": "00_distance.ipynb",
         "Hull": "00_distance.ipynb",
         "to_2dpositions": "00_distance.ipynb",
         "Hull.to_2dpositions": "00_distance.ipynb",
         "plot_atoms_and_hull": "00_distance.ipynb"}

modules = ["distance.py"]

doc_url = "https://eschmidt42.github.io/md/"

git_url = "https://github.com/eschmidt42/md/tree/master/"

def custom_doc_links(name): return None
